### ISSUE TITLE
Ed25519 Implementation

### ISSUE THREAD

**Issue by alberk8** [xoofx/Monocypher.NET#2]
I don't see the Ed25519 Signing implemented in C# code.  Is it going to be implemented?  Thank you.

**Comment by alberk8** [comment]
I am sorry that I miss the code.  I was also check out the Test Suite and could not find it there but it does show in the actual nuget install.

By the way,  is it possible to also target linux-musl-x64 and linux-musl-arm64?   Thank you.

**Comment by xoofx** [comment]
> By the way, is it possible to also target linux-musl-x64 and linux-musl-arm64? Thank you.

Please, open a separate issue, I don't have a personal interest on this but PR welcome (also never tried to do such a thing with cmake).
