### ISSUE TITLE
Monocypher v4

### ISSUE THREAD

**Issue by samuel-lucas6** [xoofx/Monocypher.NET#3]
Thought I should let you know that [Monocypher 4.0.0](https://github.com/LoupVaillant/Monocypher/releases/tag/4.0.0) was recently released and includes several additions and API changes.

**Comment by samuel-lucas6** [comment]
@xoofx [Monocypher 4.0.2](https://github.com/LoupVaillant/Monocypher/releases/tag/4.0.2) is now out. Any chance the library could be updated when you get the time? It would be great to have Argon2id and the streaming AEAD.

**Comment by xoofx** [comment]
Pushed [0.4.0](https://github.com/xoofx/Monocypher.NET/releases/tag/0.4.0) with latest Monocypher 4.0.2

I just fixed the tests but I can't tell if things are correctly mapped or accessible. It seems that the API changed quite a bit.

**Comment by samuel-lucas6** [comment]
Appreciate it! I'm going to use the new Argon2id API in a project so will let you know if I have any problems.
